### ISSUE TITLE
MissingMethodException When Using Closure For ID

### ISSUE THREAD

**Issue by chriswhitley** [NCSU-Libraries/dsci#2]
I'm attempting to use a closure to get the ID value for the records we'll be indexing.  The following command is being used.

```
java -jar dsci.jar -id closure=id.groovy marc/*.xml
```

When using this command, the following exception is shown

```sh
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static edu.ncsu.lib.dsci.Main.File() is applicable for argument types: (java.lang.String) values: [id.groovy]
Possible solutions: find(), find(groovy.lang.Closure), use([Ljava.lang.Object;), is(java.lang.Object), with(groovy.lang.Closure), wait()
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1518)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1504)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:209)
        at edu.ncsu.lib.dsci.Main.loadIDExtractor(Main.groovy:57)
        at edu.ncsu.lib.dsci.Main$loadIDExtractor.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
        at edu.ncsu.lib.dsci.Main.main(Main.groovy:104)
```

This is the `id.groovy` closure that is located in the same directory as `dsci.jar`

```groovy
// Extract the ID field from the 998$a MARC field
{ rec ->
    try { 
        rec.getVariableField('998').getSubfield('a'.charAt(0)).data
    } catch (NullPointerException npe) {
      return null
    }
}
```

This closure is just a copy past of the one in the readme with the field number changed to 998.

**Comment by adjam** [comment]
Thanks for the error report, and sorry about the bug.  

If you're just trying to get stuff working, based on your code you could replace 

`--closure=id.groovy` 
with 
`--spec= '998|a'`

**Comment by adjam** [comment]
or edit https://github.com/NCSU-Libraries/dsci/blob/master/src/main/groovy/edu/ncsu/lib/dsci/Main.groovy#L57 to say `new File(source)` instead of just `File(source)`
